BEGIN
 SELECT *
 --into l_retorna
   FROM X_MULTICLAVES M
   
  WHERE M.NRODOCEMPLEADO = '12345693'
    AND M.CLAVEINTER = '73800';
 
 SELECT *
   FROM X_MULTICLAVES M
  WHERE NRODOCEMPLEADO IN ('12345693', '79468066')
    FOR UPDATE EXCEPTION WHEN NO_DATA_FOUND THEN L_RETORNA := 0;
WHEN
OTHERS THEN L_RETORNA := 0;
END;
